# Generated by Django 2.1.1 on 2018-09-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wstreet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhistory',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
