# Generated by Django 2.0.4 on 2018-09-21 06:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wstreet', '0003_auto_20180921_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='buytable',
            name='buytime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='profile',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='selltable',
            name='selltime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cash',
            field=models.IntegerField(default=380000),
        ),
    ]
